parameters:
#    Data
    csv_data: {'App\Entity\Question':'../config/resources/questions.csv'}
    json_data: {'App\Entity\Question':'../config/resources/questions.json'}


#    Application
    default_language: en
    output_encoding: ISO-639-1
