services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Controller\QuestionsController:
        arguments:
            - '@App\Service\QuestionService'
        calls:
            - [setSerializer, ['@jms_serializer.serializer']]
        tags: ['controller.service_arguments']
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Data Providers
    App\Service\Provider\CsvDataProvider:
        arguments:
            - '%csv_data%'
        calls:
            - [setSerializer, ['@jms_serializer.serializer']]
    App\Service\Provider\JsonDataProvider:
        arguments:
            - '%json_data%'
        calls:
            - [setSerializer, ['@jms_serializer.serializer']]

    # Services
    App\Service\TranslatorService:
        arguments:
            - '%default_language%'
            - '%default_language%'
            - {'oe':'%output_encoding%'}

    App\Service\QuestionService:
        arguments:
            - '@App\Service\Provider\CsvDataProvider'
            - '@App\Service\TranslatorService'